# .woodpecker.yml
when:
  branch: [master]

steps:
  main:
    image: docker.io/artixlinux/base

    commands:
      - pacman -Syu --noconfirm base-devel git sudo nano rust
      - echo 'MAKEFLAGS="-j$(nproc --all)"' >> /etc/makepkg.conf
      - cat sudoers >> /etc/sudoers
      - useradd yay
      - usermod -aG wheel yay
      - mkdir /home/yay
      - chown -R yay:yay /home/yay
      - chown -R yay:yay "$(pwd)"
      - sudo -u yay makepkg -si --noconfirm
